### ISSUE TITLE
Deserialization fails with new xisf files after latest Pixinsight update

### ISSUE THREAD

**Issue by Steffenhir** [sergio-dr/xisf#4]
Hi, we have been using your xisf library in our gradient removal software GraXpert for quite some time and I want to thank you for your work! After the latest Pixinsight update which changed the way how astrometric metadata is stored in the xisf file, users report that the deserialization fails. 

```
2024-01-16 06:55:31,778 MainProcess root INFO     Unsupported Property type F64Vector: <Element '{http://www.pixinsight.com/xisf}Property' at 0x29edb36f0>
2024-01-16 06:55:31,890 MainProcess root ERROR    An error occurred while loading your picture.
Traceback (most recent call last):
  File "graxpert/application/app.py", line 223, in on_load_image
  File "graxpert/astroimage.py", line 49, in set_from_file
  File "xisf.py", line 134, in __init__
  File "xisf.py", line 156, in _read
  File "xisf.py", line 186, in _analyze_header
  File "xisf.py", line 189, in <dictcomp>
  File "xisf.py", line 607, in _process_property
  File "ast.py", line 110, in literal_eval
  File "ast.py", line 109, in _convert
  File "ast.py", line 83, in _convert_signed_num
  File "ast.py", line 74, in _convert_num
  File "ast.py", line 71, in _raise_malformed_node
ValueError: malformed node or string on line 1: <ast.Name object at 0x288a678e0>
```

**Comment by sergio-dr** [comment]
Thanks for the report! I tested today on a recently processed file and met the same error, caused by improper handling of boolean properties. I think [fded3bb](https://github.com/sergio-dr/xisf/commit/fded3bb0ad43d84b63c7b49beea2201bb23095fa) solves it. I pushed this as v0.9.4 on pypi.
I still have to find time to add support for the matrix and vector types...
CS, Sergio

**Comment by sergio-dr** [comment]
Hi again @Steffenhir, I've commited https://github.com/sergio-dr/xisf/commit/e37d65a9f825079d69d0a626c4bf5c5ecfac7ed0 (v0.9.5, not yet in pypi) with (hopefully) support for Vector and Matrix properties, so that astrometric solutions could be preserved. In my preliminary tests seems to work fine, you are welcome if you would like to try it and give me some feedback. Thanks!

**Comment by Steffenhir** [comment]
Hi, thank you! I will test it sometime next week.
CS Steffen

**Comment by Steffenhir** [comment]
Nevermind, I just tested it. When I retrieve the metadata of a .xisf file with xisf.get_file_metadata() and then save a new xisf with xisf.write() (specifying the metadata), the astrometric solution can not be found in Pixinsight.

This is what the xisf metadata looks like with xisf.get_file_metadata():
```
{'geometry': (6100, 4057, 3), 'sampleFormat': 'Float32', 'bounds': '0:1', 'colorSpace': 'RGB', 'location': ('attachment', 12288, 296972400), 'dtype': dtype('float32'), 'FITSKeywords': {'COMMENT': [{'value': '', 'comment': "FITS (Flexible Image Transport System) format is defined in 'Astronomy"}, {'value': '', 'comment': "and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H"}, {'value': '', 'comment': 'PixInsight Class Library: PCL 2.6.5'}, {'value': '', 'comment': 'FITS module version 1.2.0'}], 'PROGRAM': [{'value': 'PixInsight 1.8.9-2', 'comment': 'Software that created this HDU'}], 'ROWORDER': [{'value': 'TOP-DOWN', 'comment': 'Order of pixel rows stored in the image array'}], 'INSTRUME': [{'value': 'veTEC571M', 'comment': 'Name of instrument'}], 'IMAGETYP': [{'value': 'Master Light', 'comment': 'Type of integrated image'}], 'XPIXSZ': [{'value': '3.76', 'comment': 'Pixel size including binning, X-axis (um)'}], 'YPIXSZ': [{'value': '3.76', 'comment': 'Pixel size including binning, Y-axis (um)'}], 'XBINNING': [{'value': '1.', 'comment': 'Pixel binning factor, X-axis'}], 'YBINNING': [{'value': '1.', 'comment': 'Pixel binning factor, Y-axis'}], 'TELESCOP': [{'value': 'EDPH94', 'comment': 'Name of telescope'}], 'OBJECT': [{'value': 'Horsehead Nebula', 'comment': 'Name of observed object'}], 'RA': [{'value': '84.94732192292621', 'comment': 'Right ascension of the center of the image (deg)'}], 'DEC': [{'value': '-2.39097194420443', 'comment': 'Declination of the center of the image (deg)'}], 'DATE-OBS': [{'value': '2024-01-09T00:28:02.865', 'comment': 'Start date/time of observation (UTC)'}], 'DATE-END': [{'value': '2024-01-09T00:31:02.866', 'comment': 'End date/time of observation (UTC)'}], 'OBSGEO-L': [{'value': '7.122', 'comment': 'Geodetic longitude of observation location (deg)'}], 'OBSGEO-B': [{'value': '49.31', 'comment': 'Geodetic latitude of observation location (deg)'}], 'OBSGEO-H': [{'value': '340', 'comment': 'Geodetic height of observation location (m)'}], 'FOCALLEN': [{'value': '414.44043', 'comment': 'Focal length (mm)'}], 'TIMESYS': [{'value': 'UTC', 'comment': 'Time scale: Universal Time, Coordinated'}], 'STRETCH': [{'value': 'No Stretch', 'comment': ''}], 'LONG-OBS': [{'value': '7.122', 'comment': 'Geodetic longitude (deg) (compatibility)'}], 'LAT-OBS': [{'value': '49.31', 'comment': 'Geodetic latitude (deg) (compatibility)'}], 'ALT-OBS': [{'value': '340', 'comment': 'Geodetic height (m) (compatibility)'}], 'OBJCTRA': [{'value': '5 39 47.357', 'comment': 'Right ascension (hours) (compatibility)'}], 'OBJCTDEC': [{'value': '-2 23 27.50', 'comment': 'Declination (deg) (compatibility)'}]}, 'XISFProperties': {'ProcessingHistory': {'id': 'BackgroundExtraction', 'type': 'String', 'value': 'GraXpert'}}}
```

And this is what the metadata looks like with the newly created xisf file:
```
{'geometry': (6100, 4057, 3), 'sampleFormat': 'Float32', 'bounds': '0:1', 'colorSpace': 'RGB', 'location': ('attachment', 12288, 296972400), 'dtype': dtype('float32'), 'FITSKeywords': {'COMMENT': [{'value': '', 'comment': "FITS (Flexible Image Transport System) format is defined in 'Astronomy"}, {'value': '', 'comment': "and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H"}, {'value': '', 'comment': 'PixInsight Class Library: PCL 2.6.5'}, {'value': '', 'comment': 'FITS module version 1.2.0'}], 'PROGRAM': [{'value': 'PixInsight 1.8.9-2', 'comment': 'Software that created this HDU'}], 'ROWORDER': [{'value': 'TOP-DOWN', 'comment': 'Order of pixel rows stored in the image array'}], 'INSTRUME': [{'value': 'veTEC571M', 'comment': 'Name of instrument'}], 'IMAGETYP': [{'value': 'Master Light', 'comment': 'Type of integrated image'}], 'XPIXSZ': [{'value': '3.76', 'comment': 'Pixel size including binning, X-axis (um)'}], 'YPIXSZ': [{'value': '3.76', 'comment': 'Pixel size including binning, Y-axis (um)'}], 'XBINNING': [{'value': '1.', 'comment': 'Pixel binning factor, X-axis'}], 'YBINNING': [{'value': '1.', 'comment': 'Pixel binning factor, Y-axis'}], 'TELESCOP': [{'value': 'EDPH94', 'comment': 'Name of telescope'}], 'OBJECT': [{'value': 'Horsehead Nebula', 'comment': 'Name of observed object'}], 'RA': [{'value': '84.94732192292621', 'comment': 'Right ascension of the center of the image (deg)'}], 'DEC': [{'value': '-2.39097194420443', 'comment': 'Declination of the center of the image (deg)'}], 'DATE-OBS': [{'value': '2024-01-09T00:28:02.865', 'comment': 'Start date/time of observation (UTC)'}], 'DATE-END': [{'value': '2024-01-09T00:31:02.866', 'comment': 'End date/time of observation (UTC)'}], 'OBSGEO-L': [{'value': '7.122', 'comment': 'Geodetic longitude of observation location (deg)'}], 'OBSGEO-B': [{'value': '49.31', 'comment': 'Geodetic latitude of observation location (deg)'}], 'OBSGEO-H': [{'value': '340', 'comment': 'Geodetic height of observation location (m)'}], 'FOCALLEN': [{'value': '414.44043', 'comment': 'Focal length (mm)'}], 'TIMESYS': [{'value': 'UTC', 'comment': 'Time scale: Universal Time, Coordinated'}], 'STRETCH': [{'value': 'No Stretch', 'comment': ''}], 'LONG-OBS': [{'value': '7.122', 'comment': 'Geodetic longitude (deg) (compatibility)'}], 'LAT-OBS': [{'value': '49.31', 'comment': 'Geodetic latitude (deg) (compatibility)'}], 'ALT-OBS': [{'value': '340', 'comment': 'Geodetic height (m) (compatibility)'}], 'OBJCTRA': [{'value': '5 39 47.357', 'comment': 'Right ascension (hours) (compatibility)'}], 'OBJCTDEC': [{'value': '-2 23 27.50', 'comment': 'Declination (deg) (compatibility)'}]}, 'XISFProperties': {'ProcessingHistory': {'id': 'BackgroundExtraction', 'type': 'String', 'value': 'GraXpert'}}}
```

But I wouldn't rule out user error at this point or maybe the .xisf file is not new enough.

**Comment by sergio-dr** [comment]
Hi, many thanks for testing. The astrometric solution generated by PixInsight is tied to the image metadata; in the output of `xisf.get_images_metadata()[0]` you need to look for `PCL:AstrometricSolution:...` entries under key '`XISFProperties`'. 
Your output seems to come indeed from `get_images_metadata()` instead of `get_file_metadata()`, but anyway it appears that your .xisf file doesn't have an astrometric solution (or xisf cannot extract it from the original file for some reason). 
You may use `example\xisfmeta.py -x path_to/file.xisf ` to check the XML header as-is:

```
<?xml version='1.0' encoding='utf-8'?>
<xisf xmlns="http://www.pixinsight.com/xisf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:schemaLocation="http://www.pixinsight.com/xisf http://pixinsight.com/xisf/xisf-1.0.xsd">
    <Image id="integration" geometry="6224:4168:1" sampleFormat="Float32" bounds="0:1" colorSpace="Gray" location="attachment:245760:103766528">
...
        <Property id="PCL:AstrometricSolution:Catalog" type="String">Gaia DR3</Property>
        <Property id="PCL:AstrometricSolution:CelestialPoleNativeCoordinates" type="F64Vector" length="2" location="inline:base64">AAAAAACAZkAAAAAAAIBWQA==</Property>
        <Property id="PCL:AstrometricSolution:CreationTime" type="TimePoint" value="2024-01-16T16:24:11.133Z" />
        <Property id="PCL:AstrometricSolution:CreatorApplication" type="String">PixInsight 1.8.9-2</Property>
        <Property id="PCL:AstrometricSolution:CreatorModule" type="String">ImageSolver 6.2</Property>
        <Property id="PCL:AstrometricSolution:CreatorOS" type="String">Windows</Property>
        <Property id="PCL:AstrometricSolution:LinearTransformationMatrix" type="F64Matrix" rows="2" columns="2" location="inline:base64">ZYBq+71IQL/m0tjrEsXvPru57pQtmu++7ChiLltNQL8=</Property>
...
```

**Comment by Steffenhir** [comment]
Hi, thank you very much! I noticed that it was indeed user error. I overwrote the metadata dictionary under the key 'XISFProperties' with a new dictionary instead of putting a new key-value pair into the existing dictionary. Now it works perfectly!
CS Steffen

**Comment by sergio-dr** [comment]
Excellent, thanks for testing!
